### ISSUE TITLE
Run into issues with special characters 

### ISSUE THREAD

**Issue by jtalfresco** [olivierthereaux/oldtweets#7]
Error output is
`UnicodeEncodeError: 'ascii' codec can't encode character u'\u0ca0' in position 13: ordinal not in range(128)`

I was able to get around this by replacing 
`str(tweet.text).replace('\n', '').replace('\r', '')`
with
`tweet.text.encode('utf-8').strip()`

Not sure it is a better replacement but it worked for me.

**Comment by olivierthereaux** [comment]
That sounds good @jtalfresco - would you like to send as a PR?

**Comment by jtalfresco** [comment]
PR submitted

**Comment by olivierthereaux** [comment]
Merged
